// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbjAOF8WalX20WO8L49n83T4o-OAlnB0M',
    appId: '1:430181093606:web:007fb769ab8ae027aeab27',
    messagingSenderId: '430181093606',
    projectId: 'flutter-project-ab74f',
    authDomain: 'flutter-project-ab74f.firebaseapp.com',
    storageBucket: 'flutter-project-ab74f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOd4aDNl88y-EatcOfZkxB_VOR_rip9xQ',
    appId: '1:430181093606:android:8fa90805a4f46323aeab27',
    messagingSenderId: '430181093606',
    projectId: 'flutter-project-ab74f',
    storageBucket: 'flutter-project-ab74f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpbjdW5aTHCmN4ek1Il5hLEZojUV0RBN8',
    appId: '1:430181093606:ios:9d239b38611a9101aeab27',
    messagingSenderId: '430181093606',
    projectId: 'flutter-project-ab74f',
    storageBucket: 'flutter-project-ab74f.appspot.com',
    iosBundleId: 'com.example.recipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpbjdW5aTHCmN4ek1Il5hLEZojUV0RBN8',
    appId: '1:430181093606:ios:2fd92f1f6c4036fcaeab27',
    messagingSenderId: '430181093606',
    projectId: 'flutter-project-ab74f',
    storageBucket: 'flutter-project-ab74f.appspot.com',
    iosBundleId: 'com.example.recipe.RunnerTests',
  );
}
